
# Include global XSPICE selections for CC and other macros
#
# Copyright 1992
# Georgia Tech Research Corporation
# All Rights Reserved.
# This material may be reproduced by or for the U.S. Government
# pursuant to the copyright license under the clause at DFARS
# 252.227-7013 (Oct. 1988)
#
include /usr/local/xspice-1-0/include/make.include

install:
	cp cfunc.tpl $(ROOT)/lib/cmt/mkmoddir/cfunc.tpl
	cp ifspec.tpl $(ROOT)/lib/cmt/mkmoddir/ifspec.tpl
	cp Makefile.tpl $(ROOT)/lib/cmt/mkmoddir/Makefile.tpl
	cp mkmoddir.sh $(ROOT)/bin/mkmoddir

