
#
# Copyright 1992
# Georgia Tech Research Corporation
# All Rights Reserved.
# This material may be reproduced by or for the U.S. Government
# pursuant to the copyright license under the clause at DFARS
# 252.227-7013 (Oct. 1988)
#
# Include global XSPICE selections for CC and other macros
include /usr/local/xspice-1-0/include/make.include

install:
	cp modpath.tpl $(ROOT)/lib/cmt/mksimdir/modpath.tpl
	cp udnpath.tpl $(ROOT)/lib/cmt/mksimdir/udnpath.tpl
	cp Makefile.tpl $(ROOT)/lib/cmt/mksimdir/Makefile.tpl
	cp mksimdir.sh $(ROOT)/bin/mksimdir

