
#
# Copyright 1992
# Georgia Tech Research Corporation
# All Rights Reserved.
# This material may be reproduced by or for the U.S. Government
# pursuant to the copyright license under the clause at DFARS
# 252.227-7013 (Oct. 1988)
#
# Include global XSPICE selections for CC and other macros
include /usr/local/xspice-1-0/include/make.include


install:
	cp udnfunc.tpl $(ROOT)/lib/cmt/mkudndir/udnfunc.tpl
	cp Makefile.tpl $(ROOT)/lib/cmt/mkudndir/Makefile.tpl
	cp mkudndir.sh $(ROOT)/bin/mkudndir

