s/yyparse/mod_yyparse/g
s/yyv/mod_yyv/g
s/yydef/mod_yydef/g
s/yychk/mod_yychk/g
s/yyr2/mod_yyr2/g
s/yyr1/mod_yyr1/g
s/yypgo/mod_yypgo/g
s/yypact/mod_yypact/g
s/yyact/mod_yyact/g
s/yyexca/mod_yyexca/g
s/yyval/mod_yyval/g
s/yylval/mod_yylval/g
s/yylex/mod_yylex/g
s/yyout/mod_yyout/g
